# Generated by Django 3.2.5 on 2023-08-31 16:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_stuff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('2a109cee-a4ff-48d2-8a3e-06ab26cca529'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
