# Generated by Django 3.2.5 on 2023-08-31 16:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20230831_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('7a3ec48d-938d-4867-a8d5-0e8ddd7cd864'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
