# Generated by Django 3.2.5 on 2023-09-18 13:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20230831_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('182b12c3-ff07-4418-8d8e-b803ecefb2f3'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
