# Generated by Django 3.2.5 on 2023-09-19 10:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20230918_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('d869e830-550b-4bd7-8746-2cbf69e75a0c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
