# Generated by Django 3.2.5 on 2023-09-19 11:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20230919_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('21f82c71-5727-48a8-aa51-2807f9f3a8ea'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
