# Generated by Django 3.2.5 on 2023-09-19 19:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('478311a3-5db3-471a-aab8-60fd3067a56b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
