# Generated by Django 3.2.5 on 2023-12-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_rename_assets_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='cryptocurrency_code',
            field=models.CharField(default='x', max_length=5),
            preserve_default=False,
        ),
    ]
